"""initial

Revision ID: 2a8a430e4363
Revises: 
Create Date: 2026-05-10 19:47:52.339212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8a430e4363'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros',
    sa.Column('nivel_foco', sa.Integer(), nullable=False),
    sa.Column('tempo_minutos', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    # ### end Alembic commands ###
